import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

import { HiCamera, HiPencil, HiLocationMarker, HiUsers } from "react-icons/hi";
import { BsPlusCircleFill } from "react-icons/bs";
import {
  RiMoreFill,
  RiListSettingsFill,
  RiLayoutGridFill,
  RiShareForwardLine,
} from "react-icons/ri";
import { AiFillHeart, AiOutlineInstagram, AiOutlineLike } from "react-icons/ai";
import { IoMdSettings } from "react-icons/io";
import { RxHamburgerMenu } from "react-icons/rx";
import { BiComment, BiWorld } from "react-icons/bi";
import {
  FaRegBookmark,
  FaRegChartBar,
  FaRegArrowAltCircleRight,
  FaRegUser,
} from "react-icons/fa";
import Header from "../components/Header";

export default function Home() {
  const [togglePassword, setTogglePassword] = useState(false);
  const [load, setLoad] = useState(false);
  return (
    <>
      <Head>
        <title>Facebook Clone Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Header />
      <div className="w-full h-[46.9rem] lg:h-[39.4rem] flex justify-center items-center bg-[#242424]">
        <div className="bg-[#1c1c1d] h-full w-full max-w-[60rem]">
          <div className="w-full sm:h-[25.3rem] h-[20rem] rounded-b-lg bg-gradient-to-t from-black/50 to-transparent flex items-end justify-end pr-5 pb-5 lg:pr-10 lg:pb-5">
            <div className="flex items-center gap-2 bg-white py-2 px-3 rounded-md text-xl duration-150 cursor-pointer hover:bg-white/90">
              <HiCamera />
              <h2 className="font-medium text-base lg:flex hidden">
                Añadir foto de portada
              </h2>
            </div>
          </div>
          <div className="w-full px-3 relative bg-[#242424]">
            <div className="w-full flex-row lg:justify-between lg:flex">
              <div className="w-full flex flex-col lg:flex items-center gap-5 relative">
                <div className="absolute bottom-36 lg:bottom-5 lg:left-0 w-44 h-44 rounded-full flex items-center justify-center cursor-pointer border-4 border-[#242424]">
                  <Image
                    width={3000}
                    height={3000}
                    priority
                    className="w-full h-full object-cover rounded-full"
                    src="/profile.jpeg"
                    alt="Profile"
                  />
                  <div className="absolute bottom-3 right-0 bg-[#424242] text-white/90 text-2xl w-9 h-9 rounded-full flex items-center justify-center duration-150 cursor-pointer hover:bg-[#4e4e4e]">
                    <HiCamera />
                  </div>
                  <div className="absolute w-full h-full bg-white/5 rounded-full duration-100 hover:bg-white/10"></div>
                </div>
                <div className="flex flex-col gap-2 py-6 ml-0 mt-16 items-center lg:ml-12 lg:items-start lg:mt-0">
                  <p className="text-white text-4xl font-bold">
                    Sebastián Giraldo
                  </p>
                  <p className="w-28 text-white/60 font-medium text-lg hover:underline cursor-pointer">
                    105 amigos
                  </p>
                  <div className="flex">
                    <div className="bg-[#424242] border border-[#313133] w-8 h-8 rounded-full flex items-center justify-center duration-150 cursor-pointer hover:bg-[#4e4e4e]">
                      <Image
                        width={3000}
                        height={3000}
                        priority
                        className="w-full h-full object-cover rounded-full"
                        src="/profile1.jpg"
                        alt="Profile"
                      />
                    </div>

                    <div className="bg-[#424242] border border-[#313133] w-8 h-8 rounded-full flex items-center justify-center duration-150 cursor-pointer hover:bg-[#4e4e4e]">
                      <Image
                        width={3000}
                        height={3000}
                        priority
                        className="w-full h-full object-cover rounded-full"
                        src="/profile2.jpg"
                        alt="Profile"
                      />
                    </div>

                    <div className="bg-[#424242] border border-[#313133] w-8 h-8 rounded-full flex items-center justify-center duration-150 cursor-pointer hover:bg-[#4e4e4e]">
                      <Image
                        width={3000}
                        height={3000}
                        priority
                        className="w-full h-full object-cover rounded-full"
                        src="/profile3.jpg"
                        alt="Profile"
                      />
                    </div>

                    <div className="bg-[#424242] border border-[#313133] w-8 h-8 rounded-full flex items-center justify-center duration-150 cursor-pointer hover:bg-[#4e4e4e]">
                      <Image
                        width={3000}
                        height={3000}
                        priority
                        className="w-full h-full object-cover rounded-full"
                        src="/profile4.jpg"
                        alt="Profile"
                      />
                    </div>

                    <div className="bg-[#424242] border border-[#313133] w-8 h-8 rounded-full flex items-center justify-center duration-150 cursor-pointer hover:bg-[#4e4e4e]">
                      <Image
                        width={3000}
                        height={3000}
                        priority
                        className="w-full h-full object-cover rounded-full"
                        src="/profile5.jpg"
                        alt="Profile"
                      />
                    </div>

                    <div className="bg-[#424242] border border-[#313133] w-8 h-8 rounded-full flex items-center justify-center duration-150 cursor-pointer hover:bg-[#4e4e4e]">
                      <Image
                        width={3000}
                        height={3000}
                        priority
                        className="w-full h-full object-cover rounded-full"
                        src="/profile6.jpg"
                        alt="Profile"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className="w-full justify-center pb-5 lg:w-1/2 flex lg:items-end lg:justify-end gap-2 lg:py-5">
                <div className="flex items-center gap-2 bg-blue-600 text-white py-2 px-3 rounded-md duration-150 cursor-pointer hover:bg-blue-500">
                  <BsPlusCircleFill />
                  <h2 className="font-medium text-sm">Añadir a historia</h2>
                </div>
                <div className="flex items-center gap-2 bg-white/10 text-white py-2 px-3 rounded-md duration-150 cursor-pointer hover:bg-white/20">
                  <HiPencil />
                  <h2 className="font-medium text-sm">Editar perfil</h2>
                </div>
              </div>
            </div>
            <div className="w-full h-[1px] bg-white/10"></div>
            <div className="pt-1 flex items-center justify-between">
              <ul className="text-white/60 font-medium text-lg flex gap-0">
                <li className="text-blue-500 border-b-2 border-blue-500 duration-150 cursor-pointer py-3 px-4">
                  Publicaciones
                </li>
                <li className="duration-150 cursor-pointer hover:bg-white/10 py-3 px-4 rounded-md mb-1">
                  Información
                </li>
                <li className="duration-150 cursor-pointer hover:bg-white/10 py-3 px-4 rounded-md mb-1 hidden md:block">
                  Amigos
                </li>
                <li className="duration-150 cursor-pointer hover:bg-white/10 py-3 px-4 rounded-md mb-1 hidden md:block">
                  Fotos
                </li>
                <li className="duration-150 cursor-pointer hover:bg-white/10 py-3 px-4 rounded-md mb-1 hidden lg:block">
                  Vídeos
                </li>
                <li className="duration-150 cursor-pointer hover:bg-white/10 py-3 px-4 rounded-md mb-1 hidden lg:block">
                  Visitas
                </li>
                <li className="duration-150 cursor-pointer hover:bg-white/10 py-3 px-4 rounded-md mb-1 hidden lg:block">
                  Ver más
                </li>
              </ul>
              <div className="flex text-white/70 text-2xl bg-white/5 py-2 px-3 rounded-md duration-150 cursor-pointer hover:bg-white/10">
                <RiMoreFill />
              </div>
            </div>
          </div>

          <div className="flex flex-col lg:flex-row items-start gap-3 m-3 pb-3">
            <div className="w-full lg:w-3/4 flex flex-col gap-3">
              <div className="w-full flex flex-col gap-3 bg-[#242424] rounded-md py-3 px-4 pb-5">
                <h1 className="text-white font-medium text-2xl">Detalles</h1>
                <div className="flex flex-col items-center gap-3">
                  <p className="text-white cursor-text">Full Stack Developer</p>
                  <button className="w-full rounded-md py-2 duration-150 bg-white/10 hover:bg-white/20 text-white font-medium">
                    Editar presentación
                  </button>
                </div>
                <div className="w-full mt-1 flex flex-col gap-3">
                  <div className="w-full flex items-center gap-3 text-white text-xl">
                    <HiLocationMarker className="text-white/70 text-2xl" />
                    <h1 className="flex gap-1 text-base">
                      De <p className="font-semibold">Ibagué</p>
                    </h1>
                  </div>

                  <div className="w-full flex items-center gap-3 text-white text-xl">
                    <AiFillHeart className="text-white/70 text-2xl" />
                    <h1 className="flex gap-1 text-base">Soltero</h1>
                  </div>

                  <div className="w-full flex items-center gap-3 text-white text-xl">
                    <AiOutlineInstagram className="text-white/70 text-2xl" />
                    <a
                      rel="noreferrer"
                      target="_blank"
                      aria-label="Github"
                      className="text-base text-blue-400 hover:underline"
                      href="https://www.instagram.com/codewithsebas/"
                    >
                      codewithsebas
                    </a>
                  </div>

                  <button className="w-full rounded-md py-2 duration-150 bg-white/10 hover:bg-white/20 text-white font-medium">
                    Editar detalles
                  </button>
                </div>
              </div>
              <div className="w-full bg-[#242424] rounded-md py-2 px-4 flex justify-between items-center">
                <h1 className="text-white font-bold text-xl hover:underline">
                  Fotos
                </h1>
                <h1 className="text-blue-400 text-lg hover:bg-white/10 duration-150 py-1 px-3 rounded-md cursor-pointer">
                  Ver todas las fotos
                </h1>
              </div>
            </div>
            <div className="w-full flex flex-col gap-3">
              <div className="w-full flex flex-col gap-4 bg-[#242424] rounded-md py-3 px-4">
                <div className="flex gap-2">
                  <div className="w-10 h-10 flex items-center justify-center cursor-pointer ">
                    <Image
                      width={40}
                      height={10}
                      priority
                      className="w-full h-full object-cover rounded-full"
                      src="/profile.jpeg"
                      alt="Profile"
                    />
                  </div>

                  <input
                    className=" bg-[#383838] rounded-full duration-150  w-full text-start px-4 outline-none text-white font-normal text-lg hover:bg-[#4e4e4e]"
                    placeholder="¿Qué estás pensando?"
                  />
                </div>
                <div className="w-full h-[1px] bg-white/10"></div>
                <div className="flex justify-around">
                  <div className="flex gap-2 items-center text-white/60 font-medium hover:text-white duration-150 cursor-pointer">
                    <div className="w-6 h-6">
                      <Image
                        width={3000}
                        height={3000}
                        priority
                        className="w-full h-full object-cover"
                        src="/vivo.png"
                        alt="Vivo"
                      />
                    </div>
                    <p>Vídeo en directo</p>
                  </div>

                  <div className="flex gap-2 items-center text-white/60 font-medium hover:text-white duration-150 cursor-pointer">
                    <div className="w-6 h-6">
                      <Image
                        width={3000}
                        height={3000}
                        priority
                        className="w-full h-full object-cover"
                        src="/foto.png"
                        alt="Vivo"
                      />
                    </div>
                    <p>Foto/vídeo</p>
                  </div>
                </div>
              </div>
              <div className="w-full bg-[#242424] rounded-md">
                <div className="flex-row gap-5 md:items-center justify-between py-3 px-4 md:flex">
                  <h1 className="text-white text-xl font-semibold">
                    Publicaciones
                  </h1>
                  <div className="flex-row md:flex gap-3">
                    <button className="mt-2 md:mt-0 flex items-center gap-1 text-white bg-white/10 rounded-md py-1 px-3 text-base duration-150 hover:bg-white/20">
                      <RiListSettingsFill />
                      <p>Filtros</p>
                    </button>
                    <button className="mt-2 md:mt-0 flex items-center gap-1 text-white bg-white/10 rounded-md py-1 px-3 text-base duration-150 hover:bg-white/20">
                      <IoMdSettings />
                      <p>Administrar publicaciones</p>
                    </button>
                  </div>
                </div>
                <div className="w-full h-[1px] bg-white/10"></div>
                <div className="flex justify-between px-4">
                  <button className="w-full flex justify-center items-center gap-2 text-blue-500 border-b-2 border-blue-500 duration-150 cursor-pointer py-1 px-4">
                    <RxHamburgerMenu className="text-xl" />
                    <h1>Vista de lista</h1>
                  </button>
                  <button className="w-full flex justify-center items-center gap-2 rounded-md text-white/60 hover:bg-white/10 duration-150 cursor-pointer py-1 px-4 my-1">
                    <RiLayoutGridFill className="text-xl" />
                    <h1>Vista de cuadrícula</h1>
                  </button>
                </div>
              </div>

              <div className="flex flex-col gap-2 w-full bg-[#242424] rounded-md py-3 px-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-10 h-10 rounded-full relative">
                      <Image
                        width={3000}
                        height={3000}
                        priority
                        className="w-full h-full object-cover rounded-full"
                        src="/profile.jpeg"
                        alt="Vivo"
                      />
                      <div className="w-3 h-3 bg-green-500 rounded-full absolute bottom-0 right-0 border-2 border-[#242424] flex"></div>
                    </div>
                    <div className="flex flex-col">
                      <h1 className="text-white font-medium">
                        Sebastián Giraldo
                      </h1>
                      <p className="text-white/50 flex items-center gap-1">
                        7 h - <HiUsers />
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center justify-center w-10 h-10 text-white/70 text-2xl duration-150 cursor-pointer hover:bg-white/5 rounded-full">
                    <RiMoreFill />
                  </div>
                </div>
                <div className="w-full h-full border border-white/10 rounded-2xl">
                  <Image
                    width={3000}
                    height={3000}
                    priority
                    src="/public.jpg"
                    alt=""
                    className="rounded-t-2xl object-cover w-full h-full border-b border-white/5"
                  />

                  <div className="flex items-center gap-3 py-2 px-3 ">
                    <div className="w-10 h-10 rounded-full">
                      <Image
                        width={3000}
                        height={3000}
                        priority
                        className="w-full h-full object-cover rounded-full"
                        src="/page.jpg"
                        alt="Vivo"
                      />
                    </div>
                    <div className="flex flex-col">
                      <h1 className="text-white font-medium">The Man Charly</h1>
                      <p className="text-white/50 flex items-center gap-1">
                        2 d - <BiWorld />
                      </p>
                    </div>
                  </div>
                  <p className="text-white px-4 pb-3">2004</p>
                </div>
                <div className="flex justify-between gap-1">
                  <button className="w-full flex items-center justify-center gap-1 py-1 rounded-md duration-150 hover:bg-white/10 text-white/60">
                    <AiOutlineLike className="text-[1rem] md:text-2xl" />
                    <h1 className="text-[0.7rem] font-medium md:text-base">
                      Me gusta
                    </h1>
                  </button>

                  <button className="w-full flex items-center justify-center gap-1 py-1 rounded-md duration-150 hover:bg-white/10 text-white/60">
                    <BiComment className="text-[1rem] md:text-2xl" />
                    <h1 className="text-[0.7rem] font-medium md:text-base">
                      Comentar
                    </h1>
                  </button>

                  <button className="w-full flex items-center justify-center gap-1 py-1 rounded-md duration-150 hover:bg-white/10 text-white/60">
                    <RiShareForwardLine className="text-[1rem] md:text-2xl" />
                    <h1 className="text-[0.7rem] font-medium md:text-base">
                      Compartir
                    </h1>
                  </button>
                </div>
                <div className="w-full h-[1px] bg-white/10"></div>
                <div className="flex gap-2">
                  <div className="rounded-full flex items-center justify-center cursor-pointer">
                    <Image
                      width={3000}
                      height={3000}
                      priority
                      className="w-9 h-9 object-cover rounded-full"
                      src="/profile.jpg"
                      alt="Profile"
                    />
                  </div>
                  <div className="bg-[#383838] w-full rounded-full relative flex items-center justify-between gap-1">
                    <input
                      className="bg-transparent w-full h-full outline-none px-4 text-white/60 font-normal text-sm"
                      type="text"
                      placeholder="Escribe un comentario..."
                    />
                    <div className="flex pr-2 text-base">
                      <div className=" hover:bg-white/5 duration-150 p-1.5 text-white/60 rounded-full flex items-center justify-center cursor-pointer">
                        <FaRegUser />
                      </div>
                      <div className=" hover:bg-white/5 duration-150 p-1.5 text-white/60 rounded-full flex items-center justify-center cursor-pointer">
                        <FaRegArrowAltCircleRight />
                      </div>
                      <div className=" hover:bg-white/5 duration-150 p-1.5 text-white/60 rounded-full flex items-center justify-center cursor-pointer">
                        <FaRegChartBar />
                      </div>
                      <div className=" hover:bg-white/5 duration-150 p-1.5 text-white/60 rounded-full flex items-center justify-center cursor-pointer">
                        <FaRegBookmark />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
